package calve23.moduleoptimizer;

public enum LinkEffectName {
    STRENGTH_BOOST,
    AGILITY_BOOST,
    INTELLECT_BOOST,
    SPECIAL_ATTACK,
    ELITE_STRIKE,
    HEALING_BOOST,
    HEALING_ENHANCE,
    RESISTANCE,
    ARMOR,
    CAST_FOCUS,
    ATTACK_SPD,
    CRIT_FOCUS,
    TEAM_LUCK_AND_CRIT,
    FINAL_PROTECTION,
    LIFE_CONDENSE,
    FIRST_AID,
    LIFE_STEAL,
    LIFE_WAVE,
    AGILE,
    DMG_STACK,
    LUCK_FOCUS;
}
